name: Build TFT Top-30 Comps

on:
  workflow_dispatch:
    inputs:
      RIOT_API_KEY:
        description: "Paste your 24h Riot dev key"
        required: true
        type: string

permissions:
  contents: write

concurrency:
  group: comp-stats
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: true }

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Generate comps.json
        env:
          RIOT_API_KEY: ${{ inputs.RIOT_API_KEY }}
          PLATFORM: na1
          REGION: americas
          MIN_SAMPLE: "10"
          SEED_PLAYERS: "20"
          COUNT_PER: "3"
          RATE_DELAY_MS: "1300"
          QUEUES: "1100"
        run: node scripts/update_comp_stats.mjs

      - name: Commit & push JSON
        run: |
          if [ -f public/data/comps.json ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/data/comps.json
            git diff --cached --quiet || git commit -m "chore: refresh comps.json"
            git push
          else
            echo "comps.json not produced; keeping previous file"
            exit 1
          fi
